name: f1investor_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  bloc: ^9.2.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  go_router: ^17.2.3
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/

flutter_native_splash:
  color: "#080808"
  image: assets/imagenes/f1_logo.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#080808"
    image: assets/imagenes/f1_logo_android12.png
    icon_background_color: "#080808"